# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  fb_api_version: <%= ENV["FB_API_VERSION"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  fb_app_access_token: <%= ENV["FB_APP_ACCESS_TOKEN"] %>
  fb_user_access_token: <%= ENV["FB_USER_ACCESS_TOKEN"] %>
  google_client_id: <%= ENV["google_client_id"] %>
  google_client_secret: <%= ENV["google_client_secret"] %>
  secret_key_base: 7807a8628c03e394e96e3ddd701a0709ce817f6ac33df127823e1c51c6b8ce8155f0cf24a41ebae41819cc958d61b8612cd245ed96219152fee4915665eae6f2

test:
  secret_key_base: 47425a81d68dc5da47a338321a6fb3d3b798ec49b12989b6b61dd10532eab9f8c85c7d76acc410137741a58476a2d6297598d1114fd1c43ef82f4978f9ace469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  fb_api_version: <%= ENV["FB_API_VERSION"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  fb_app_access_token: <%= ENV["FB_APP_ACCESS_TOKEN"] %>
  fb_user_access_token: <%= ENV["FB_USER_ACCESS_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
